#!/usr/bin/env bash

# Colors for output
# shellcheck disable=SC2034
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_color() {
    printf "${!1}%s${NC}\n" "$2"
}

# Function to run a command and check its result
run_command() {
    print_color "YELLOW" "Running $1"
    result=$($2)
    exit_code=$?

    if [ $exit_code -ne 0 ]; then
        echo -e "$result \n"
        print_color "RED" "$3"
        exit 1
    fi

    echo "$result"
    print_color "GREEN" "Finished running $1 successfully"
}

# Run flutter test
#run_command "flutter test" "flutter test" "One or more tests failed, please fix them before pushing"
#
#print_color "GREEN" "All tests passed. Proceeding with the push."
#exit 0