name: portfolio
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.4.5
  flutter_dotenv: ^5.2.1
  easy_localization: ^3.0.7
  logger: ^2.5.0
  json_theme_plus: ^6.8.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  animated_text_kit: ^4.2.3
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  riverpod_lint: ^2.6.5
  flutter_gen_runner: ^5.10.0

flutter:

  uses-material-design: true
  fonts:
    - family: Mali
      fonts:
        - asset: assets/fonts/Mali/Mali-Bold.ttf
        - asset: assets/fonts/Mali/Mali-BoldItalic.ttf
        - asset: assets/fonts/Mali/Mali-ExtraLight.ttf
        - asset: assets/fonts/Mali/Mali-ExtraLightItalic.ttf
        - asset: assets/fonts/Mali/Mali-Italic.ttf
        - asset: assets/fonts/Mali/Mali-Light.ttf
        - asset: assets/fonts/Mali/Mali-LightItalic.ttf
        - asset: assets/fonts/Mali/Mali-Medium.ttf
        - asset: assets/fonts/Mali/Mali-MediumItalic.ttf
        - asset: assets/fonts/Mali/Mali-Regular.ttf
        - asset: assets/fonts/Mali/Mali-SemiBold.ttf
        - asset: assets/fonts/Mali/Mali-SemiBoldItalic.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/techs/
    - assets/translations/
    - assets/env/
    - assets/fonts/Mali/
    - assets/data/
    - assets/data/about_me/
    - assets/data/base/
    - assets/data/experiences/
    - assets/data/home/
    - assets/data/skills/
