name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'
          
      - name: Check Flutter version
        run: flutter --version
        
      - name: Create env files
        run: |
          echo "BASE_URL=" > assets/env/.env.dev
          echo "BASE_URL=" > assets/env/.env.stg
          echo "BASE_URL=" > assets/env/.env.prod
      
      - name: Enable Web
        run: flutter config --enable-web
        
      - name: Get dependencies
        run: flutter clean && flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs && dart run easy_localization:generate -S assets/translations -O lib/gen && dart run easy_localization:generate -S assets/translations -s en-US.json -O lib/gen -o locale_keys.g.dart -f keys && dart fix --apply && dart format .
        
      - name: Build
        run: flutter build web --release --base-href /portfolio/ -t lib/flavors/main_dev.dart canvaskit

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/web
